FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04

RUN apt-get update && apt-get install -y \
  git \
  wget \
  python3 \
  python3-pip \

# Install from pip
RUN pip3 install mxnet-cu90

# RUN apt-get install -y iproute2

WORKDIR /app
COPY main.py /app/main.py
COPY entrypoint.sh /app/entrypoint.sh
ENTRYPOINT ["/bin/bash", "/app/entrypoint.sh"]
